export const KeywordsData = {
  Dental: [
    "Best Dental Clinic in {{area}}",
    "Best Dentist in {{area}}",
    "Best Dental Hospital Near {{area}}",
    "Best Dental Doctor in {{area}}",
    "Best Dental Specialist in {{area}}",
    "Best Pediatric Dentist Near {{area}}",
    "Best Dental Clinic for Children in {{area}}",
    "Best Dental Clinic for Childre in {{area}}",
    "Best Dental Clinic for Childr in {{area}}",
    "Best Dental Clinic for Child in {{area}}",
    "Best Dental Treatment in {{area}}",
    "Best Kids Dentist in {{area}}",
    "Top Dentist in {{area}}",
  ],
  Gynecology: [
    "Best Gynecology Hospital in {{area}}",
    "Best Gynecologist in {{area}}",
    "Best Pregnancy Hospital in {{area}}",
    "Best Gynecology DOctor in {{area}}",
    "Best Gynecology Doctor in {{area}}",
    "Gynecologist Near me in {{area}}",
    "Top Gynecology Hospital in {{area}}",
    "Best Infertility Clinic in {{area}}",
    "Normal Delivery Hospital in {{area}}",
    "Caesarean Delivery in {{area}}",
    "C - Section Doctor in {{area}}",
    "High Risk Pregnancy Care in {{area}}",
    "Pregnancy Control Clinic in {{area}}",
  ],
  Orthopedics: [
    "Best Pain Specialist in {{area}}",
    "Best Pain Management Specialist in {{area}}",
    "Best Back Pain Doctor in {{area}}",
    "Best Orthopedician in {{area}}",
    "Best Orthopedic Hospital in {{area}}",
    "Best Knee Pain Specialist in {{area}}",
    "Top Orthopedician in {{area}}",
    "Best Orthopedic Surgeon in {{area}}",
    "Best Joints Pain Specialist in {{area}}",
    "Best Spine Specialist in {{area}}",
    "Best Arthritis Pain Specialist in {{area}}",
    "Best Neck & Shoulde Pain Doctor in {{area}}",
  ],
  Neurology: [
    "Top Neuro Hospital in {{area}}",
    "Top Neurology Doctor in {{area}}",
    "Best Neurovascular Surgeon in {{area}}",
    "Best Neuro Surgeon in {{area}}",
    "Best Neurologist in {{area}}",
    "Best Brain & Spine Specialist in {{area}}",
    "Best Neuro Doctor in {{area}}",
    "Best Neurology Clinic in {{area}}",
    "Best Brain Stroke Hospital in {{area}}",
    "Best Neuro Physician in {{area}}",
    "Best Doctor for Brain Tumor in {{area}}",
    "Best Neurologist Near me in {{area}}",
    "Best Neurology & Neuro Surgery Doctor in {{area}}",
  ],
  Urology: [
    "Best Urology Hospital in {{area}}",
    "Best Urologist in {{area}}",
    "Best Andrologist in {{area}}",
    "Best Urology Specialist in {{area}}",
    "Best Urology Center in {{area}}",
    "Best Male Fertility Doctor in {{area}}",
    "Best Kidney Stones Clinic in {{area}}",
    "Best Kidney Stones removal in {{area}}",
    "Best Male Fertility Treatment in {{area}}",
    "Best Doctor for Prostate Cancer in {{area}}",
    "Best Kidney Center in {{area}}",
    "Best Kidney Doctor in {{area}}",
    "Best Treatment for Premature Ejaculation in {{area}}",
    "Best Doctor for Urinary Tract Infection in {{area}}",
  ],
  Pulmonology: [
    "Best Pulmonology Hospital in {{area}}",
    "Best Pulmonology Specialist in {{area}}",
    "Best Lungs Doctor in {{area}}",
    "Best Doctor for Asthama in {{area}}",
    "Best Hospital for Breathing Problem in {{area}}",
    "Pulmonology Clinic Near me in {{area}}",
    "Best Pulmonologist in {{area}}",
    "Best Asthama Treatment in {{area}}",
    "Best Respiratory Care in {{area}}",
    "Pulmonology Doctor in {{area}}",
    "Top Specialist for Breathing issues in {{area}}",
  ],
  Gastroenterology: [
    "Best Gastroenterologist in {{area}}",
    "Best Gastro Center in {{area}}",
    "Best Gastro Hospital Near me in {{area}}",
    "Best Gastroenterology Specialist in {{area}}",
    "Best Doctor for Gastric Problem in {{area}}",
    "Best Gastro Surgeon in {{area}}",
    "Laparascopic Gastroenterologist in {{area}}",
    "Best Herina Surgeon in {{area}}",
    "Best Piles Doctor Near me in {{area}}",
    "Top Laparoscopic Surgeon in {{area}}",
    "Best Proctologist in {{area}}",
    "Best Treatment for Piles in {{area}}",
    "Best Laparoscopic Piles Surgery in {{area}}",
  ],
};
